### ISSUE TITLE
html large size 

### ISSUE THREAD

**Issue by ariannafebbo** [csoneson/countsimQC#6] opened 2022-07-12 11:49 UTC
Hi, I tried to run your package first in my personal laptop (Microsoft Windows 11 Education) with two count matrices and the html output size was 3.5MB. Then for runtime issues I tried to run your package with two count matrices (one was the same as the previously used, and one was smaller in rows compared to the second previously used) in a server (Linux master 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux) and the html output size was of almost 1GB. Consequently I could not open the generated html. 
I tried to split in 4 files the html output to take a look at the image size. It looked like the images generated were heavy (300kB), while in the one generated in Windows they were pretty light (around 15kB).
Please can you help me solve it, by generating in Linux System a smaller http output?

**Comment by csoneson** [comment] 2022-07-14 11:16
Hi @ariannafebbo - thanks for raising the issue. I can reproduce it with the current settings. I can also make the Windows and Linux output approximately the same size by changing the plot backend - however, this increases the Windows output size rather than decreasing the Linux one...I'll look into ways of hopefully getting them both a bit smaller and get back to you.

**Comment by csoneson** [comment] 2022-07-16 12:59
Hi @ariannafebbo - I just pushed an update to the `plot-size` branch that hopefully should address this. If you set `useRAGG=TRUE` in the call to `countsimQCReport()`, you can also specify a `dpi` value, which lets you control the resolution of the plots. If you decrease this from the default 96, the report should be smaller. You can install the updated version from GitHub using 

```
remotes::install_github("csoneson/countsimQC", ref = "plot-size")
```

**Comment by ariannafebbo** [comment] 2022-07-21 09:38
Thank you very much @csoneson . 
For other users to know, I found out that large html files can most likely be opened with Firefox, among all other browsers.

**Comment by csoneson** [comment] 2022-07-22 09:12
Thanks for the update. I'm going to close this issue (and push the changes to the Bioc devel branch) as I think the problem is resolved - feel free to reopen if you still run into trouble with this.

**Closed as completed by csoneson** 2022-07-22 09:12 UTC
